name: CI

on:
  - push

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npx prettier --check .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: |
          npx ng test ngx-url-serializer --watch=false --browsers=ChromeHeadless
          npx ng test demo --watch=false --browsers=ChromeHeadless
          npx ng build demo

  build:
    runs-on: ubuntu-latest

    needs:
      - format
      - test

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: |
          npx ng build ngx-url-serializer
          cp README.md dist/ngx-url-serializer

      - uses: JS-DevTools/npm-publish@v4
        if: github.ref_name == 'main'
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/ngx-url-serializer
          tag: latest
          access: public
          strategy: upgrade

      - uses: anothrNick/github-tag-action@v1
        if: github.ref_name == 'main' && steps.publish.outputs.type
        env:
          CUSTOM_TAG: ${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: softprops/action-gh-release@v2
        if: github.ref_name == 'main' && steps.publish.outputs.type
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          body: "Changelog: https://github.com/soc221b/ngx-url-serializer/blob/${{ steps.publish.outputs.version }}/projects/ngx-url-serializer/CHANGELOG.md"
